version: "3"

services:
  mysql:
    build:
      context: .
      dockerfile: docker/mysql/Dockerfile
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - "3306:3306"
    environment:
        MYSQL_ROOT_PASSWORD: 1234
        MYSQL_DATABASE: base
    volumes:
      - mysql-db-data:/var/lib/mysql
    networks:
      - base

  nginx:
    build:
      context: .
      dockerfile: docker/nginx/Dockerfile
    ports:
      - "80:80"
    expose:
      - "9008"
    networks:
      - base
    volumes:
      - .:/var/www/project
    depends_on:
      - php

  php:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
      args:
        TIMEZONE: ${TIMEZONE}
    volumes:
      - .:/var/www/project
    expose:
      - "9008"
    networks:
      - base
    depends_on:
      - mysql

networks:
  base:

volumes:
  mysql-db-data: